### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by conorwhyman** [agsimeonov/cse305#1]
Hello,

Would it be possible to provide any model solution to assignment 2? 

Thank you

**Comment by agsimeonov** [comment]
Hi @conorwhyman,

All of the assignments should include a working and correct solution as far as I recall.  As this was completed around 6 years ago I don't quite remember if anything is missing from them.  If you find an alternate/better solution or something incomplete, feel free to create a pull request and I'd be happy to merge it in.
